locale = "ru"
site_title = "Монтелиберо"
site_subtitle = "Проект Свободного Общества в Европе"
meta_description = "Либертарианский социальный эксперимент в Черногории"
project_of_tfm = "Проект Третьего Фонда Монтелиберо"

[what_is_montelibero]
header = "Что такое Монтелиберо?"
text = """
Монтелиберо - это движение по переезду либертарианцев в Черногорию и построению в ней свободного общества на либертарианских принципах.

Что это за принципы? Вкратце: свободный рынок и неагрессия. 

Если вы цените человеческую жизнь, чтите частную собственность, уважаете чужие навыки и честный бизнес, от государства хотите только чтобы оно от вас отстало, да и вообще полагаете, что государства создают проблем куда больше, чем решают - вполне вероятно, что вы либертарианец, даже если сейчас впервые прочитали это слово.

[Более подробная статья о либертарианстве](https://sozidatel.com/2022/06/13/who-are-libertarians/)
\\
[Еще более подробная брошюрка о либертарианстве](https://ancapchan.info/ancap/)
"""

[population]
header = "Рост сообщества"
text = """
Первые поселенцы Монтелиберо приехали в Черногорию в декабре 2021. Резкий рост сообщества случился после начала горячей фазы войны в Украине. Сейчас приток эмигрантов из России замедлился, и мы в основном прирастаем диаспорой. Еще к нам присоединяются выходцы из излишне зарегулированных стран ЕС, в первую очередь, Германии. 
(дать примерный график численности)
"""

[growth]
header = "Развитие сообщества"
text = """
Либертарианство - это про дух предпринимательства. На свободном рынке ты преуспеваешь тем больше, чем больше пользы приносишь окружающим. Преуспевание может выражаться как в деньгах, так и в социальном капитале.
Многие из участников Монтелиберо уже запустили тот или иной бизнес. На отдельной вики-страничке (ссылка) мы постарались перечислить тех, кого упомнили. Если кого-то забыли - просто впишите себя туда.
Но есть множество проектов, где во главу угла ставится прежде всего не прибыль, а улучшение инфраструктуры Монтелиберо. О них чуть позже, а пока пара слов о нашем экономическом движке:

"""

[tokenomics]
header = "Токеномика"
text = """
Что это? Вкратце: это экономика, основанная на обмене токенами - то есть записями в публичном реестре, описывающем те или иные имущественные права. Лучше познакомьтесь с более подробным описанием (ссылка на статью про токеномику), это вам в любом случае пригодится.
Через токеномику мы стараемся описывать почти все наши экономические отношения. Почему? Потому что это оказался удобный мостик между онлайном и офлайном, ведь участники проекта живут не только в Черногории, но и по всему миру.
А теперь вернемся к инфраструктурным проектам

"""

[eurmtl]
header = "EURMTL"
text = """
В Черногории ходит евро, но страна официально не часть еврозоны. Поэтому банковский функционал тут довольно скромный. EURMTL - это наш стейблкоин на евро, его мы используем между собой вместо безнала. Например, чтобы поделить чек в кафе.
Обеспечение EURMTL - обыкновенные наличные евро, которые лежат понемногу у наших казначеев. В их обязанности входит хранить кэш, обменивать его в обе стороны на EURMTL без комиссии, периодически проводить аудит. Часть EURMTL обеспечена в избыточном размере другими ликвидными активами, вроде биткоина.

"""

[MTL]
header = "MTL"
text = """
На заре Монтелиберо денег в проекте было мало, и мы сложили их в общую кубышку, наш инвестиционный фонд. Токены MTL - это акции фонда. Фонд координирует систему EURMTL и многих других инструментов токеномики. Им управляет двадцатка крупнейших акционеров.
Главная задача фонда - привлекать деньги со всего мира и вкладывать их в развитие проекта Монтелиберо - как в бизнес, так и в инфраструктуру.

"""

[meetings]
header = "МТЛ-завтраки и МТЛ-ланчи"
text = """
Пока инвестиционный фонд Монтелиберо привлекает со всего мира деньги, в самой Черногории активисты привлекают людей, которые краем уха что-то слышали о проекте, и хотели бы познакомиться. Раз в неделю проходит МТЛ-завтрак, и раз в неделю - МТЛ-ланч. Люди собираются в кафе, знакомятся, неформально общаются, задают вопросы о проекте, смотрят, как работает наша токеномика в повседневных расчетах. А потом в какой-то момент начинают говорить про либертарианцев и про проект Монтелиберо не “они”, а “мы”. 
"""

[fcm]
header = "Первый клуб Монтелиберо"
text = """
Людям мало знать, что они либертарианцы. Им важно еще и находиться среди единомышленников. Это самый веский стимул для примыкания к сообществу. Редких встреч в кафе для этого недостаточно.
Первый клуб Монтелиберо - это место, где либертарианцы чувствуют себя, как дома. Поэтому, извините, резидентами клуба становятся не все подряд. Сперва человек приходит в качестве гостя, приглашенного одним из резидентов. Потом с ним знакомятся и решают, принять ли его в клуб.

"""

[city]
header = "МТЛ-Сити"
text = """
Проводить вечера в клубе - это здорово, но отчего бы либертарианцам и вовсе не поселиться по соседству? Летом 2021 фонд МТЛ и несколько частных лиц купили гектар земли. Потом поделили между собой пропорционально вложениям. Расчистили. Построили дорогу. Провели электричество и интернет. Построили водохранилище и канализацию. Ну и, конечно, принялись строить дома.
В конце мая 2023 года в МТЛ-Сити появился первый постоянный житель. На середину 2023 года сданы два жилых дома: трехэтажный восьмиквартирник на земле фонда и дом-глэмпинг “геосфера” на одном из частных участков.
Стройка продолжается.

"""